name: Entrega continua

on:
    workflow_call:

jobs:

    EC2:
        runs-on: ubuntu-latest
        steps:
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.8 # actions/download-artifact@v3.0.0
          with:
        # Artifact name
            name: programa
        - uses: actions/checkout@v4.1.7 # actions/checkout@v3

        - name: Deploy to Staging server
          uses: easingthemes/ssh-deploy@main
          with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }} 
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: /home/${{ secrets.REMOTE_USER }}
            EXCLUDE: "postgres-data"

        - name: executing remote ssh commands
          uses: appleboy/ssh-action@master
          env:
            DBHOST: ${{ secrets.DBHOST }}
            DBUSER: ${{ secrets.DBUSER }}
            DBPASSWORD: ${{ secrets.DBPASSWORD }}
            DBNAME: ${{ secrets.DBNAME }}
            DBPORT: ${{ secrets.DBPORT }}
            PORT: 8000
          with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            envs: DBHOST, DBUSER, DBPASSWORD, DBNAME, DBPORT, PORT
            script: |
              echo "DBHOST: $DBHOST"
              echo "PORT: $PORT"
              chmod +x main.go
              go run ./main.go > nohup.out 2> nohup.err < /dev/null &

          # uses: fifsky/ssh-action@master
          # with:
          #   command: |
          #     sudo su
          #     export DBUSER=${{ secrets.DBUSER }}
          #     export DBPASSWORD=${{ secrets.DBPASSWORD }}
          #     export DBNAME=${{ secrets.DBNAME }}
          #     export DBPORT=${{ secrets.DBPORT }}
          #     export PORT=8000
          #     chmod +x main.go
          #     go run ./main.go > nohup.out 2> nohup.err < /dev/null &
          #   host: ${{ secrets.REMOTE_HOST }}
          #   user: ${{ secrets.REMOTE_USER }}
          #   key: ${{ secrets.SSH_PRIVATE_KEY }}

